@startuml BackendStore

!include ./regex_tags.puml
!include ./filters.puml
!include ./logs.puml

package OopsieLogsy #LightYellow {
    package Backend #White {
        struct Store #LightSalmon {
            + regex_tags : RegexTagsManager
            + logs : LogsManager
            + filters : FilterTabsManager

            + static get_instance() : LockReadGuard<Store>
            + static get_instance_mut() : LockWriteGuard<Store>
        }

        Store -down-> RegexTagsManager : has
        Store -down-> LogsManager : has
        Store -down-> FilterTabsManager : has
    }
}

@enduml